apiVersion: apps/v1
kind: Deployment
metadata:
  name: hadoop-datanode
  labels:
    app: hadoop-datanode
spec:
  selector:
    matchLabels:
      app: hadoop-datanode
  replicas: 2
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: hadoop-datanode
    spec:
      containers:
        - image: bde2020/hadoop-datanode:latest
          imagePullPolicy: Always
          name: hadoop-datanode
          env:
          - name: SERVICE_PRECONDITION
            value: hadoop-service:9000
          - name: CORE_CONF_fs_defaultFS
            value: hdfs://hadoop-service:9000
