apiVersion: apps/v1
kind: Deployment
metadata:
  name: hadoop-namenode
  namespace: "default"
  labels:
    app: hadoop-namenode
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hadoop-namenode
  template:
    metadata:
      labels:
        app: hadoop-namenode
    spec:
      containers:
      - name: hadoop-namenode
        image: bde2020/hadoop-namenode:latest
        env:
        - name: CLUSTER_NAME
          value: test
        - name: CORE_CONF_fs_defaultFS
          value:hdfs://hadoop-service:9000
        - name: CORE_CONF_hadoop_http_staticuser_user
          value: root
        - name: CORE_CONF_hadoop_proxyuser_hue_hosts
          value: *
        - name: CORE_CONF_hadoop_proxyuser_hue_groups
          value: *
        - name: CORE_CONF_io_compression_codecs
          value: org.apache.hadoop.io.compress.SnappyCodec
        - name: HDFS_CONF_dfs_webhdfs_enabled
          value: true
        - name: HDFS_CONF_dfs_permissions_enabled
          value: false
        - name: HDFS_CONF_dfs_namenode_datanode_registration_ip___hostname___check
          value: false
